# Generated by Django 2.2.4 on 2022-02-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='id',
            field=models.CharField(default='e5ca9fac-6a78-4048-9820-f5a16369fa6d', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
