# Generated by Django 2.2.4 on 2022-02-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='id',
            field=models.CharField(default='965017f3-08db-48ee-9ba8-ecc8e984a51d', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
