# Generated by Django 2.2.4 on 2022-02-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220131_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='Teste',
            field=models.CharField(default='Desconhecido', max_length=30),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='id',
            field=models.CharField(default='e1ea745f-5e86-4869-af7c-d63d7823ad2a', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
