# Generated by Django 2.2.4 on 2022-02-23 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220223_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='id',
            field=models.CharField(default='2216ccf6-2c18-4b76-84b4-b8391513fb13', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicoproduto',
            name='criados',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Criação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='criados',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Criação'),
        ),
    ]
