# Generated by Django 2.2.4 on 2022-02-23 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220223_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='id',
            field=models.CharField(default='bc100480-17d6-4b66-9e30-cda88f8b06ea', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicoproduto',
            name='criados',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 16, 57, 41, 663304), verbose_name='Criação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='criados',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 16, 57, 41, 663304), verbose_name='Criação'),
        ),
    ]
