# Generated by Django 2.2.4 on 2022-02-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220210_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='id',
            field=models.CharField(default='dda36720-5976-4d04-ac59-138cbb4ca822', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
