# Generated by Django 2.2.4 on 2022-02-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220210_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='id',
            field=models.CharField(default='c86687a7-dd9b-4f7c-92ec-7bf38cc87803', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
