# Generated by Django 2.2.4 on 2022-02-24 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220223_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoproduto',
            name='dia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicoproduto',
            name='hora',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='id',
            field=models.CharField(default='1b36558e-7171-407b-87b9-1b2bbba60684', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicoproduto',
            name='criados',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 17, 21, 0, 20357), verbose_name='Criação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='criados',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 17, 21, 0, 20357), verbose_name='Criação'),
        ),
    ]
