# Generated by Django 2.2.4 on 2022-02-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220210_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='Teste',
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='id',
            field=models.CharField(default='91087022-44bc-4b23-807d-17d8edfbd92e', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
