# Generated by Django 2.2.4 on 2022-02-24 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220224_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoproduto',
            name='ano',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicoproduto',
            name='mes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='id',
            field=models.CharField(default='0f2829a3-733d-4dbb-ab47-7705ef849f31', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicoproduto',
            name='criados',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 17, 27, 10, 187610), verbose_name='Criação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='criados',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 17, 27, 10, 187610), verbose_name='Criação'),
        ),
    ]
