# Generated by Django 2.2.4 on 2022-02-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220214_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusuario',
            old_name='endereco',
            new_name='logradouro',
        ),
        migrations.RenameField(
            model_name='customusuario',
            old_name='estado',
            new_name='uf',
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='id',
            field=models.CharField(default='2a16e311-657f-4a6b-b65d-ae41fb18c17e', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
