# Generated by Django 2.2.4 on 2022-02-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220216_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='id',
            field=models.CharField(default='f09926ea-4e61-47bc-bb27-eff66dfe7c00', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
