# Generated by Django 2.2.4 on 2022-02-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220216_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusuario',
            old_name='logradouro',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='customusuario',
            old_name='uf',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='id',
            field=models.CharField(default='c7e904f3-a2a3-473f-93d7-9953d8671dc2', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
