# Generated by Django 2.2.4 on 2022-02-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220216_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusuario',
            old_name='endereco',
            new_name='logradouro',
        ),
        migrations.RenameField(
            model_name='customusuario',
            old_name='estado',
            new_name='uf',
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='id',
            field=models.CharField(default='7b685e1a-ba0d-46ab-89e3-bedef153f516', max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
